spring:
  application:
    name: eureka-client
server:
  port: 8001

info:
  app:
    name: eureka-client
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true         # 启用接口关闭 Spring Boot


# 服务注册
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

