spring:
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.91.23:8848
    #   server-addr: localhost:8848
    #   namespace: 917f93f6-2850-41ab-8496-2e8285f037ad
    sentinel:
      transport:
        # 指定 sentinel 控制台地址
        dashboard: localhost:8080


  datasource:
    url: jdbc:mysql://123.56.91.23:3306/content_center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maxLifetime: 30000
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource

server:
  port: 8881

info:
  app:
    name: content-center
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    # feign 的日志系统是建立在 SpringBoot 基础上的，此处一定要是 debug，否则都不会打印
    com.soft1851.content.center.feignclient.UserCenterFeignClient: debug

rocketmq:
  name-server: 123.56.91.23:9876
  producer:
    # 必须指定group
    group: test-group

# feign 配置日志
feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的 urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50



