server:
  port: 8002

# 服务注册
eureka:
  instance:
    hostname: jie.com
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/

spring:
  application:
    name: mysql-client
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/db_blog?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 30000
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource


#Mybatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-enums-package: com.soft1851.mysqlclient.entity
  global-config:
    db-config:
      #主键类型:auto主键自增，input用户输入id，id_worker全局唯一的数字id，UUID全局唯一的UUID
      id-type: auto
      #开启驼峰转换
      table-underline: true
