server:
  port: 7001
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: jie.com     # 主机名
    prefer-ip-address: true     # 是否将当前服务的IP注册到 Eureka Server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://jie.com:7001/eureka/