spring:
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:     # 配置 Nacos 元数据
          instance: cc
          version: 1.0
#        namespace: 917f93f6-2850-41ab-8496-2e8285f037ad

server:
  port: 6002

info:
  app:
    name: content-center
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true



